### ISSUE TITLE
how to integrate ngx-admin in vs2017 project

### ISSUE THREAD

**Issue by masterchen** [ttma1046/asp.net-core-ngx-admin#1]

**Comment by ttma1046** [comment]
What's exactly you mean by VS 2017 project ?  ASP.NET MVC ? ASP.NET WEB API ?

I can use vs 2017 to create millions of different type of project.

**Comment by ttma1046** [comment]
说中文吧。

**Comment by masterchen** [comment]
你用dotnet command 创建的工程， 我意思是是否可以才用aspnet core 在vs中创建一个完整的项目

**Comment by ttma1046** [comment]
刚试下了，是可以的，用visual studio 2017 创建一个asp.net core web application 项目，选择“angular”模板，然后删掉clientapp文件夹的里的东西，git clone ngx-admin的源码到clientapp里，编译成功，能运行的。
用vs 2017创建asp.net core 项目和命令行创建无异。

**Comment by masterchen** [comment]
thanks
