### ISSUE TITLE
Need clarification on the final step

### ISSUE THREAD

**Issue by Eternal21** [ttma1046/asp.net-core-ngx-admin#2]
Thanks for creating this repo, it was the only place that actually listed the steps required to get ngx-admin working with .Net Core.  I have one question.  At the end your readme, you state the following:

> Had reverted back the fetch-data.component inside of pages folder.
> https://localhost:5001/#/pages/fetch-data

Can you clarify what you mean by that?

**Comment by ttma1046** [comment]
Hi, thanks for star.
I remeber the fetch-data.component is just a demo component in the project created via `dotnet new angular`.
It gets deleted after step 3.

I just think maybe revert it back and move it inside the ngx-admin might help some developer who knows about `dotnet new angular` but not familiar 'ngx-admin'.
